### PR TITLE
Update of background and minor changes

### PR DESCRIPTION
**Pull request by mkovatsc**
Dear @xdfy 

I made a pass and focused on the contributions I wanted to make to the background section. I saw that you already included what I had in mind -- I polished a bit the view I got to know from working with OT companies.

I also applied some conventions I prefer, but this is the usual discussion about writing style...
* Usage of Oxford comma
* Treat areas of Computer Science as proper names, e.g., "Cloud Computing", "Edge Computing", ...
* Aim for one sentence per line -- this simplifies merging and understanding changes a lot

### CODE REVIEW

**Comment by mkovatsc** [comment]
Oh, and removed the redundancy between abstract and introduction -- I do not really see a value in repeating word by word, just for the sake of having a longer intro :P

**Comment by mkovatsc** [comment]
Thanks a lot for all the work you others put in!

**Comment by xdfy** [comment]
Thanks Matthias. One editorial point about the capitalization of terms (for consistency between editors). I checked capitalization of terms like "edge computing" and "cloud computing" in existing drafts and RFCs. It is overwhelmingly in lower case (except when a specific rule applies, like titlecase or when used in a specific entity's name like Multi-access Edge Computing). So I would propose to revert back to the lower case version of those terms for the general case.

I agree that if we just say "the Fog", it is similar to "the Internet" and capitalization makes sense, while "fog computing" this is similar to "cloud/edge computing" and lowercase seems more appropriate.

**Comment by xdfy** [comment]
Well, actually I'd just like to clarify that it is of course not that important at the end. If you have a good non-ambiguous rule to determine what to capitalize, it's fine too. If we can minimize the number of terms that we capitalize, that will make the text more readable IMO.

**Comment by mkovatsc** [comment]
Hi @xdfy 

I know that RFCs tend to write everything lowercase, but I never heard a good explanation, why for instance, "the Internet" or "the Web" would not be a proper name. Funnily, a discussion during my paper writing days about "the cloud" determined that it should be lowercase, as there are many clouds and not the only one properly named one; I would apply a similar logic to "the fog".

I rethought about the names such as cloud computing. When we treat them as common fields of study, I agree we should go for lowercase. Before I treated them as proper names for the technology, but even edge computing has become quite common...

Since the PR is still open, I will apply the quick search&replace fix.

**Comment by mkovatsc** [comment]
Done.

Also went for American English in the usage of "e.g." and "i.e.", i.e., with a comma after.

**Comment by xdfy** [comment]
Thanks, merging and will update the editors' HTML accordingly

**Pull request merged**
